server:
  port: 8081

spring:
  datasource:
    url: postgresql://dpg-d7gmftpf9bms73eispdg-a.oregon-postgres.render.com/noite_database
    username: admin
    password: asGhwfiJnyJperOP1xnhPJF9lkb50IxS
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

  sql:
    init:
      mode: always
      schema-locations: classpath:schema-postgresql.sql
      platform: postgres