-- CREATE TABLE IF NOT EXISTS USERS  (
--     ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
--     USERNAME VARCHAR(40),
--     HANDLE VARCHAR(20)
-- );

CREATE TABLE IF NOT EXISTS POST (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    -- USER_ID UUID,
    CONTENT VARCHAR(256),
    STARS INT DEFAULT 0,
    REPOSTS INT DEFAULT 0
    -- FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

