CREATE TABLE IF NOT EXISTS USERS  (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    CREATED_AT TIMESTAMP DEFAULT NOW(),
    USERNAME VARCHAR(40),
    HANDLE VARCHAR(20),
    PASSWORD VARCHAR(128),
    PICTURE TEXT
);

CREATE TABLE IF NOT EXISTS POSTS (
    UUID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    CREATED_AT TIMESTAMP DEFAULT NOW(),
    USER_ID UUID REFERENCES USERS(ID) ON DELETE CASCADE,
    CONTENT VARCHAR(256),
    STARS INT DEFAULT 0,
    REPOSTS INT DEFAULT 0,
    REPLY_POST_ID UUID DEFAULT NULL
);